name: Update GitHub Profile with HTB Stats

on:
  schedule:
    - cron: "0 */6 * * *"  # runs every 6 hours
  workflow_dispatch:       # allows you to run it manually

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: README.md
          token: ${{ secrets.METRICS_TOKEN }}

          base: ""
          plugin_hackthebox: yes
          plugin_hackthebox_user: AviralxRoot
